# Generated by Django 4.2.16 on 2024-11-20 07:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Emailserver',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('emailid', models.CharField(max_length=255, null=True, unique=True)),
                ('sender', models.CharField(max_length=255)),
                ('cc', models.EmailField(max_length=255)),
                ('mail_server', models.EmailField(max_length=255)),
                ('mail_port', models.IntegerField()),
                ('mail_use_tls', models.BooleanField(default=True)),
                ('mail_use_ssl', models.BooleanField(default=False)),
                ('username', models.EmailField(max_length=255)),
                ('password', models.EmailField(max_length=255)),
                ('active', models.EmailField(default='No', max_length=255)),
            ],
        ),
    ]
